export const GET_BOOKS_REQUEST="GET_BOOKS_REQUSET"
export const GET_BOOKS_SUCCESS="GET_BOOKS_SUCCESS"
export const GET_BOOKS_ERROR="GET_BOOKS_ERROR"

export const PATCH_BOOK_SUCCESS="PATCH_BOOK_SUCCESS";